package dk.StudyBobby.backend.entities;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import jakarta.persistence.Column;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.time.Duration;

@Entity // An entity is the same as a table in the database, and each instance of this class will be a row in that table.
public class AcademicSession {
    // Every time we see "@something", think of it as magic that tells the framework to do something special with this field or class.
    // In this case, "@Entity" tells Spring that this class should be stored in the database as a table.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This means that the "id" will be automatically generated by the database, and it will be unique for each user.
    private Long id;

    @ManyToOne
    @JoinColumn(name = "userId")  // Foreign key column name
    private User user;

    @Column(columnDefinition = "TIMESTAMP")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime createdAt;

    private String title;

    private String sessionType; // should be enum
    
    private int state; // should also be enum

    private Duration duration;

    // Constructors
    public AcademicSession() {}

    public AcademicSession(User user, String title, String sessionType, int state, Duration duration) {
        this.user = user;
        this.title = title;
        this.sessionType = sessionType;
        this.state = state;
        this.duration = duration;
    }

    // Getters & setters
    public Long getId() { return id; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getSessionType() { return sessionType; }
    public void setSessionType(String sessionType) { this.sessionType = sessionType; }

    public int getState() { return state; }
    public void setState(int state) { this.state = state; }

    public Duration getDuration() { return duration; }
    public void setDuration(Duration duration) { this.duration = duration; }
}