package dk.StudyBobby.backend.entities;

import jakarta.persistence.*;

@Entity // An entity is the same as a table in the database, and each instance of this class will be a row in that table.
public class Goal {
    // Every time we see "@something", think of it as magic that tells the framework to do something special with this field or class. 
    // In this case, "@Entity" tells Spring that this class should be stored in the database as a table.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This means that the "id" will be automatically generated by the database, and it will be unique for each user.
    private Long id;

    @ManyToOne
    @JoinColumn(name = "academicSessionId")  // Foreign key column name
    private AcademicSession academicSession;

    private String goal;

    // Constructors
    public Goal() {}

    public Goal(AcademicSession academicSession, String goal) {
        this.academicSession = academicSession;
        this.goal = goal;
    }

    // Getters & setters
    public Long getId() { return id; }

    public AcademicSession getAcademicSession() { return academicSession;}
    public void setAcademicSession(AcademicSession academicSession) { this.academicSession = academicSession;}

    public String getGoal() { return goal; }
    public void setGoal(String goal) {this.goal = goal; }

//    public Long getAcademicSessionId() {
//        return academicSessionId;
//    }
//    public void setAcademicSessionId(Long academicSessionId) {
//        this.academicSessionId = academicSessionId;
//    }

}