package dk.StudyBobby.backend.entities;

import jakarta.persistence.*;

@Entity // An entity is the same as a table in the database, and each instance of this class will be a row in that table.
public class Goal {
    // Every time we see "@something", think of it as magic that tells the framework to do something special with this field or class. 
    // In this case, "@Entity" tells Spring that this class should be stored in the database as a table.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This means that the "id" will be automatically generated by the database, and it will be unique for each user.
    private Long id;

    @OneToMany
    @MapsId  // Maps this entity's id to the AcademicSession's id
    @JoinColumn(name = "academicSessionId")  // Foreign key column name
    private AcademicSession academicSession;

    private Long academicSessionId;

    private String goal;

    // Constructors
    public Goal() {}

    public Goal(AcademicSession academicSession, String goal) {
        this.academicSession = academicSession;
        this.goal = goal;
    }

    // Getters & setters
    public Long getId() { return id; }

    public String getGoal() { return goal; }

    public void setGoal(String goal) { this.goal = goal; }
}