package dk.StudyBobby.backend.entities;

import jakarta.persistence.*;

@Entity // An entity is the same as a table in the database, and each instance of this class will be a row in that table.
public class User {
    // Every time we see "@something", think of it as magic that tells the framework to do something special with this field or class. In this case, "@Entity" tells Spring that this class should be stored in the database as a table.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This means that the "id" will be automatically generated by the database, and it will be unique for each user.
    private Long id;

    private String name;

    // Constructors
    public User() {}

    public User(String name) {
        this.name = name;
    }

    // Getters & setters
    public Long getId() { return id; }

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }
}