spring.application.name=backend
# SQLite connection
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate config - hibernate is a tool to avoid using SQL directly, and instead use Java objects. It needs to know which database we are using, so it can generate the correct SQL.
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional, helpful) - this will print the SQL queries that Hibernate generates to the console, which can be useful for debugging and understanding what is happening under the hood.
spring.jpa.show-sql=true